
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShortcutActivationSetting(activation: ShortcutActivation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_shortcut_activation_setting", { activation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeHoldThresholdMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_threshold_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayAfterMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReliablePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_reliable_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister all bindings while the user is recording a
 * shortcut in the UI. This avoids firing actions while keys are recorded.
 */
async suspendAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register all bindings after the user has finished recording.
 */
async resumeAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadBackendSetting(backend: VadBackend) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_backend_setting", { backend }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerWordRemovalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_word_removal_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureInputStatus() : Promise<SecureInputStatus> {
    return await TAURI_INVOKE("get_secure_input_status");
},
async runKeyboardDiagnostic(durationSecs: number | null) : Promise<Result<KeyboardDiagnosticReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_keyboard_diagnostic", { durationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async isUpdateChecksLocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_update_checks_locked");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async getMicrophoneChannels(deviceName: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_channels", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedChannel(channel: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_channel", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write the whole overlay theme to the theme file.
 * 
 * The theme file is the overlay theme, so this is where a committed change
 * from the Appearance tab lands. The frontend always sends the complete
 * twenty-two-token object: setting one token, clearing one (reset to inherit)
 * and resetting the whole theme are all this one call with a different
 * object.
 * 
 * Values are clamped before they are written, so nothing out of range reaches
 * the file, the native geometry or the frontend. The file is then read back
 * and resolved, and that resolved theme is both the answer and what goes out
 * to the two windows. Reading back is not ceremony: it makes the answer the
 * document on disk rather than the intent, and it is what lets the watcher
 * recognise Handy's own write and stay quiet.
 * 
 * A managed theme file (a symlink, or one Handy cannot write) is refused
 * here as well as locked in the tab, so the guard does not depend on the UI.
 * 
 * `async` is load-bearing: Tauri runs a sync command inline on the IPC thread
 * and spawns an `async fn` on the runtime, and the write then goes to a
 * blocking thread, so neither the main thread nor an async worker waits on
 * the filesystem.
 */
async changeOverlayThemeSetting(theme: OverlayTheme) : Promise<Result<ResolvedOverlayTheme, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Paint a theme the user is still dragging, without persisting anything.
 * 
 * The Appearance tab commits on a debounce, right for the file and far too
 * slow for the eye. It also sends the draft here, coalesced to one call per
 * animation frame, and this puts it on the overlay with nothing written, no
 * broadcast to the settings window, and no native window work unless a token
 * the window is built from moved.
 * 
 * A no-op unless a preview is running and nothing is recording, as decided by
 * `overlay_preview::accepts_theme_drafts`. Anywhere else the overlay belongs
 * to a recording, or to a preview told to stop, and is not the tab's to
 * paint.
 * 
 * Every draft that gets through leaves a mark, which
 * `change_overlay_theme_setting` clears (plain text, not an intra-doc link:
 * this doc comment is copied verbatim into `src/bindings.ts`). That
 * guarantees the screen ends on the file's own theme even when the commit
 * that follows has nothing to write, and it is why a draft is never recorded
 * as a delivery.
 */
async previewOverlayThemeDraft(theme: OverlayTheme) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_overlay_theme_draft", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The current resolved overlay theme, from the theme-file cache.
 * 
 * A pure pull. It reads the cache the show path has just refreshed, emits
 * nothing and touches no native window, so the overlay can call it inside the
 * settings read it already awaits before becoming visible. That keeps a show
 * to exactly one file read; the backend re-reads and the webview only pulls.
 */
async getResolvedOverlayTheme() : Promise<Result<ResolvedOverlayTheme, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_resolved_overlay_theme") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-read the theme file, resolve, deliver, and return the result.
 * 
 * What the Appearance tab calls on mount, and what its Reload button calls on
 * the machines where the watcher could not start. With the watcher running a
 * hand edit arrives on its own, so the button is not shown; this stays the
 * backstop, and the mount read stays because a tab opened after a change made
 * while it was closed must not show a stale theme.
 * 
 * `async` is load-bearing twice over. Tauri runs a sync command inline on the
 * IPC thread and spawns an `async fn` on the runtime, and the read then goes
 * to a blocking thread, so neither the main thread nor an async worker waits
 * on the filesystem.
 */
async reloadOverlayThemeFile() : Promise<Result<ResolvedOverlayTheme, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_overlay_theme_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the folder the theme file belongs in, creating it when it is Handy's
 * own and missing.
 * 
 * What the Appearance tab's Open button calls when no theme file exists. The
 * path it shows then is usually `~/.config/handy/overlay_theme.json`, which
 * most users have had no reason to create, so revealing it has to make it
 * first; `revealItemInDir` needs an item, and here there is none.
 * 
 * Only a directory is created, never `overlay_theme.json`, and only under
 * `~/.config/handy/`. A path named by `HANDY_OVERLAY_THEME_FILE` opens at its
 * nearest existing folder instead, Handy having been told to read it, not to
 * build a tree at it. `overlay_theme_file::reveal_target` holds that choice.
 * 
 * `async` and then `spawn_blocking`, like `reload_overlay_theme_file`. The
 * `mkdir`, its probe and the hand-off to the file manager are all filesystem
 * work, kept off the IPC thread and the async workers.
 */
async revealOverlayThemeLocation() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_overlay_theme_location") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show the real overlay and keep it there, cycling or pinned, until something
 * stops it.
 * 
 * `sample_text` is the Live panel's transcript, already translated so i18n
 * stays on the frontend. `None` falls back to built-in English. Returns as
 * soon as the overlay is up; tokens edited while it runs repaint it live.
 */
async startOverlayPreview(state: PreviewState, sampleText: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_overlay_preview", { state, sampleText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set which state the preview shows, without restarting the driver.
 * 
 * Safe while nothing is running. The pin sticks for the next start.
 */
async setOverlayPreviewState(state: PreviewState) : Promise<void> {
    await TAURI_INVOKE("set_overlay_preview_state", { state });
},
/**
 * Stop the running preview and hide the overlay. A no-op when none runs.
 */
async stopOverlayPreview() : Promise<void> {
    await TAURI_INVOKE("stop_overlay_preview");
},
/**
 * The overlay webview calls this whenever the card's shape changes.
 * 
 * The payload is a symbolic shape plus a duration, never pixels. The backend
 * recomputes the window size from its own constants and the resolved size
 * scale, and coalesces by shape identity rather than by time, so a repeated
 * report costs nothing and a real change never waits.
 * 
 * `durationMs` is how long the window may take to reach the new shape, 0
 * (snap) to 2000 ms. Anything longer is rejected, not clamped, since it would
 * leave a native window animation running long after the card settled.
 */
async setOverlayCardShape(shape: OverlayCardShape, durationMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_overlay_card_shape", { shape, durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
overlayThemeDraft: OverlayThemeDraft,
resolvedOverlayTheme: ResolvedOverlayTheme,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
overlayThemeDraft: "overlay-theme-draft",
resolvedOverlayTheme: "resolved-overlay-theme",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The container-level `serde(default)` (backed by the `Default` impl below)
 * guarantees every field — including ones added in the future — falls back to
 * its `get_default_settings()` value when missing from a stored settings
 * object, so a partial store can never fail the whole load (#1619).
 * Field-level defaults below take precedence where present.
 */
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; 
/**
 * Defaults to empty on partial stores; the load path merges in the
 * default bindings for any missing keys before the settings are used.
 */
bindings?: Partial<{ [key in string]: ShortcutBinding }>; 
/**
 * Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
 * migrated from it in `apply_settings_migrations`.
 */
shortcut_activation?: ShortcutActivation; 
/**
 * Hold-or-toggle only: a press held at least this long is push-to-talk,
 * anything shorter is a tap that locks recording on.
 */
hold_threshold_ms?: number; audio_feedback?: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes — see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; 
/**
 * Which input channel to use on the selected microphone device.
 * None means "average all channels" (original behavior).
 */
selected_channel?: number | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; theme?: Theme; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; paste_delay_after_ms?: number; 
/**
 * Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
 * after the target app actually reads the transcript, instead of after a
 * fixed delay. See `paste_tx`. macOS and Windows only.
 */
reliable_paste?: boolean; typing_tool?: TypingTool; external_script_path?: string | null; filler_word_removal_enabled?: boolean; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; 
/**
 * Stable transcribe.cpp device selector. This is derived from the backend's
 * `device_id` when available (or its name for backends such as Metal),
 * never from the process-local device registry index.
 */
transcribe_gpu_device?: string | null; extra_recording_buffer_ms?: number; vad_enabled?: boolean; 
/**
 * Experimental detector implementation. Silero remains the stable default.
 */
vad_backend?: VadBackend; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this — that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle; 
/**
 * The overlay theme as builds before the theme file became the theme
 * stored it.
 * 
 * Kept for compatibility, and read exactly once: the one-time migration
 * in `overlay_theme_write::migrate_once` copies it into
 * `~/.config/handy/overlay_theme.json`. Nothing writes it and nothing
 * resolves from it after that; `overlay_theme.json` is the overlay theme.
 */
overlay_theme?: OverlayTheme; 
/**
 * Whether the one-time migration of `overlay_theme` into the theme file
 * has run.
 * 
 * It makes "once" literal. Without it, deleting the theme file would
 * resurrect a theme the store still holds, and deleting the file has to
 * mean the overlay goes back to its built-in look.
 */
overlay_theme_migrated?: boolean }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
/**
 * Which native implementation is drawing the Glass surface.
 * 
 * Not a token but a fact about the running machine, riding alongside
 * `GlassSupport` so the Appearance tab offers what the engine honours instead
 * of guessing from a macOS version in TypeScript. On Liquid Glass that is the
 * Glass style; on the fallback, nothing.
 */
export type GlassEngine = 
/**
 * Nothing is installed: off macOS, or the install failed. Always paired
 * with `available: false`.
 */
"none" | 
/**
 * One `NSVisualEffectView`, the pre-macOS-26 blur. Honours `GlassMaterial`.
 */
"visual_effect" | 
/**
 * One `NSGlassEffectView`, which is Liquid Glass on macOS 26 and later.
 * Honours `GlassStyle` and tints itself from the surface.
 */
"liquid"
/**
 * Which macOS material the Glass blur is drawn with.
 * 
 * `material` is a live setter on the one `NSVisualEffectView`, so a swap
 * costs one property assignment. Read only while the effective Material is
 * Glass; merged and ignored on Flat and off macOS.
 * 
 * The eight `NSVisualEffectMaterial` cases that suit a small floating card,
 * most see-through first. The default measured the most backdrop transmission
 * on macOS 26, in both app themes, at the tint an unset `glass_tint` gives.
 */
export type GlassMaterial = 
/**
 * `NSVisualEffectMaterialHUDWindow`: the most see-through of the eight in
 * both app themes, and the default. It alone ignores the system
 * appearance, a fixed dark recipe that reads as contrast under the thin
 * default tint. Over a white backdrop under a Light theme it is within
 * 3 levels of Popover; over a dark one it darkens 13 levels more.
 */
"hud_window" | 
/**
 * `NSVisualEffectMaterialPopover`: follows the appearance, about two
 * thirds of HudWindow's transmission, and the pick for a card that does.
 */
"popover" | 
/**
 * `NSVisualEffectMaterialMenu`: follows the appearance, denser again.
 */
"menu" | 
/**
 * `NSVisualEffectMaterialSidebar`: follows the appearance, softer.
 */
"sidebar" | 
/**
 * `NSVisualEffectMaterialUnderWindowBackground`: the widest blur radius,
 * little transmission left.
 */
"under_window_background" | 
/**
 * `NSVisualEffectMaterialSheet`: opaque in both themes on macOS 26.
 */
"sheet" | 
/**
 * `NSVisualEffectMaterialToolTip`: follows the appearance, very light.
 */
"tooltip" | 
/**
 * `NSVisualEffectMaterialContentBackground`: opaque in both themes on
 * macOS 26.
 */
"content_background"
/**
 * Which Liquid Glass recipe `NSGlassEffectView` draws.
 * 
 * macOS 26 replaced the frosted `NSVisualEffectView` look with Liquid Glass,
 * whose two published styles are the whole choice: `Regular`, standard glass
 * dimming itself so content stays legible over anything, and `Clear`, thinner
 * and leaning on the backdrop. Read only while the liquid engine draws
 * (macOS 26 and later); merged and ignored on the fallback engine and off
 * macOS, where `GlassMaterial` is its equivalent.
 */
export type GlassStyle = 
/**
 * `NSGlassEffectViewStyleRegular`: the default, and the one that keeps a
 * transcript readable over a bright desktop.
 */
"regular" | 
/**
 * `NSGlassEffectViewStyleClear`: thinner glass, more backdrop.
 */
"clear"
/**
 * Whether Glass can render.
 */
export type GlassSupport = { 
/**
 * The platform can render Glass at all. macOS only; a compile-time fact.
 * Drives whether the Appearance tab's Glass option is selectable.
 */
supported: boolean; 
/**
 * Glass renders right now: `supported`, the effect view is installed, and
 * macOS "Reduce transparency" is off. Drives what is actually painted.
 */
available: boolean; 
/**
 * Which native view is installed, and so which of the two engine-specific
 * tokens means anything here. `None` until an install succeeds, which is
 * what off-macOS and a failed install both report.
 */
engine: GlassEngine }
export type GpuDeviceOption = { id: string; name: string; total_vram_mb: number }
/**
 * A canonical `#rrggbb` colour.
 * 
 * Lenient parsing, always lowercase `#rrggbb`: `#RGB` shorthand, a missing
 * `#`, any case and whitespace all work; 4- and 8-digit forms (alpha) and CSS
 * colour names do not. The only string reaching a CSS custom property, and
 * re-serialised from this type, so no stored value is echoed verbatim.
 */
export type HexColor = string
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardDiagnosticReport = { secure_input_enabled: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Counts only — key identity is deliberately never captured.
 */
key_down: number; key_up: number; flags_changed: number; mouse: number; duration_ms: number }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Why Handy reads the theme file but will not write it.
 * 
 * A stable, translatable identity, like `ThemeFileDiagnosticCode`. The
 * Appearance tab looks up an i18n string by reason and passes the ownership's
 * `target` as its parameter. Plain text, not an intra-doc link: this doc
 * comment is copied verbatim into `src/bindings.ts`.
 */
export type ManagedReason = 
/**
 * The file itself is a symlink. Whoever made the link owns the document,
 * which is how a dotfile or Omarchy-style setup says "this one is mine",
 * so Handy follows it to read and never writes through it.
 */
"symlink" | 
/**
 * The file is there and its permissions refuse a write.
 */
"read_only" | 
/**
 * There is no file, and this is not a path Handy creates. Only
 * `HANDY_OVERLAY_THEME_FILE` names such a path: it was given to be read.
 */
"not_creatable" | 
/**
 * The path could not be inspected at all. Reading may still have
 * succeeded from the last good document, so this locks the tab rather
 * than assuming a write would land.
 */
"unknown"
/**
 * How the overlay surface is rendered: Flat (opaque) or Glass (translucent,
 * blurring whatever is behind it).
 */
export type Material = 
/**
 * An opaque surface. The only Material outside macOS, and the fallback
 * whenever Glass cannot render.
 */
"flat" | 
/**
 * A translucent surface backed by a native blur of what is behind the
 * overlay window. macOS only.
 */
"glass"
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
/**
 * Which of the five card shapes the overlay is currently drawing.
 * 
 * Under Flat this is bookkeeping only. The window covers the widest card the
 * overlay style can reach and the CSS morph happens inside it. Under Glass
 * the window is sized from it, because the slack is zero and the Live panel's
 * open/collapsed morph is a webview decision (streamed text and phase) that
 * Rust cannot otherwise see.
 * 
 * One shape per distinct `.scard` class combination in
 * `RecordingOverlay.tsx`. The footprints mirror the `--ov-*` block in
 * `RecordingOverlay.css`, pinned by
 * `overlay_window_constants_match_overlay_css`, and must agree with
 * `cardShape()` in `src/overlay/cardShape.ts`, pinned by
 * `initial_card_shape_matches_card_shape_ts`.
 */
export type OverlayCardShape = 
/**
 * The resting Minimal pill, `.scard.compact`.
 */
"compact_rest" | 
/**
 * The Minimal working pill, `.scard.compact.cworking`, at the same
 * footprint as Live's collapsed working pill.
 */
"compact_working" | 
/**
 * The Live pill before it opens or collapses, `.scard`.
 */
"live_pill" | 
/**
 * The Live panel collapsed to its working pill, `.scard.working`.
 */
"live_working" | 
/**
 * The Live panel expanded, `.scard.open`.
 */
"live_open"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
/**
 * The twenty-two overlay-theme tokens. `None` means inherit.
 * 
 * Field names are the theme-file keys, and every field deserializes
 * leniently: a wrong type or shape degrades to `None` with a `warn!`, so one
 * bad token never costs the other twenty-one, as `salvage_settings` does one
 * level up. The store salvages silently (log only); the theme file applies
 * the same rules but reports diagnostics, so it runs its own per-key pass
 * instead of deserializing an `OverlayTheme`.
 */
export type OverlayTheme = { 
/**
 * Highlight colour: waveform bars, recording dot, caret, spinner arc.
 */
accent?: HexColor | null; 
/**
 * The card's background colour.
 */
surface?: HexColor | null; 
/**
 * The card background's alpha under Flat, 0.30 to 1.00.
 * 
 * Read only while the effective Material is Flat; under Glass the card's
 * alpha is `glass_tint`, so one theme holds both an opaque Flat card and
 * a see-through Glass one. Before the split, Glass at a high opacity
 * painted an opaque card and nothing said why.
 */
surface_opacity?: number | null; 
/**
 * How much of the `surface` colour covers the glass, 0.00 to 1.00.
 * 
 * Glass's half of the pair above: the alpha the card paints its surface
 * at while the effective Material is Glass, and the alpha the liquid
 * engine's native `tintColor` is composed at. Ignored under Flat.
 */
glass_tint?: number | null; 
/**
 * The card's foreground colour, and the base every neutral derives from.
 */
text?: HexColor | null; 
/**
 * The card's border colour, before `border_opacity`. Unset it derives
 * from `text` on both Materials, only at a stronger alpha under Glass.
 */
border?: HexColor | null; 
/**
 * The card border's alpha, 0.00 to 1.00.
 */
border_opacity?: number | null; 
/**
 * Flat or Glass. Glass renders as Flat wherever it is unavailable, so
 * what is actually painted is the resolved theme's effective material.
 */
material?: Material | null; 
/**
 * Which macOS material the Glass blur uses. Read only by the
 * `visual_effect` engine, so ignored under Flat and on macOS 26.
 * 
 * Theme-file only. Its row left the Appearance tab when Liquid Glass
 * arrived, so the merge takes it from the file, never the settings store,
 * where a value an older build persisted would drive the fallback engine
 * with no control to show or clear it. The field stays so those documents
 * deserialize and a theme copied out of the tab still round-trips.
 */
glass_material?: GlassMaterial | null; 
/**
 * Which Liquid Glass style the Glass surface uses. Read only by the
 * `liquid` engine, so ignored under Flat and before macOS 26.
 */
glass_style?: GlassStyle | null; 
/**
 * How heavy the card's drop shadow is, 0.00 to 1.00.
 * 
 * The two Materials draw a shadow in two different places, so this token
 * means two things. Under Flat it shapes a CSS `box-shadow` on the card,
 * and the window grows a symmetric margin for it to fall into. Under
 * Glass, where the window is the card, the shadow is macOS's own and
 * `NSWindow` offers no strength, so any value above zero switches it on
 * and zero switches it off.
 */
shadow_strength?: number | null; 
/**
 * How far the card's shadow is pushed below it at scale 1, 0 to 16 px.
 * 
 * Flat only. macOS places its own window shadow, so this is ignored under
 * Glass. It sizes the window's shadow slack together with the fixed blur
 * radius, so it is one of the values the native window is built from.
 */
shadow_offset_y?: number | null; 
/**
 * Whether the control row shows the waveform. Unset means it does.
 * 
 * Hiding it empties the row's centre column, and the two resting shapes
 * (the Minimal pill and the Live pill) shrink to what the row still
 * holds. The working pill and the open panel keep their tuned widths.
 */
show_waveform?: boolean | null; 
/**
 * Whether the control row shows the cancel button. Unset means it does.
 * 
 * The keyboard shortcut and `--cancel` still cancel; only the button on
 * the card goes. With it the row's side columns lose the 22 px floor that
 * existed to hold it.
 */
show_cancel?: boolean | null; 
/**
 * One factor multiplying every length in the card, 0.80 to 1.50.
 */
size_scale?: number | null; 
/**
 * The card's corner radius at scale 1, 0 to 32 px.
 */
radius?: number | null; 
/**
 * The card's border width at scale 1, 0 to 4 px. One of the two tokens
 * besides `size_scale` that change the card's footprint, so the native
 * window is computed from it.
 */
border_width?: number | null; 
/**
 * The card's inner padding on all four sides at scale 1, 0 to 20 px. The
 * control row is a fixed core plus one of these above and below, and the
 * Live transcript's inset follows, so the card grows taller with it and
 * the native window is computed from it too.
 */
padding?: number | null; 
/**
 * Extra horizontal space between the control row's elements (the dot, the
 * waveform, the timer and the cancel button) at scale 1, 0 to 40 px.
 * 
 * The row has two of these, so every card is twice the gap wider and the
 * native window follows. The centre column's room is unchanged, since the
 * card gains exactly what the two gaps take.
 */
element_gap?: number | null; 
/**
 * How the waveform is drawn. Unset means today's bars, which is the
 * enum's own default.
 * 
 * The only token nothing native reads: the waveform lane is the same
 * width whatever draws in it, so a style can never move a window, and the
 * card alone resolves the inherit. Hence no accessor beside the others.
 */
waveform_style?: WaveformStyle | null; 
/**
 * Gap between waveform bars at scale 1, 0 to 5 px.
 */
waveform_gap?: number | null; 
/**
 * Width of each waveform bar at scale 1, 2 to 6 px.
 */
waveform_width?: number | null }
/**
 * A theme being edited, on its way to the overlay window alone.
 * 
 * The same payload as `ResolvedOverlayTheme` under a second name, since the
 * name is the whole distinction. A draft is not persisted, so the overlay
 * paints it without mirroring it to localStorage, and the Appearance tab,
 * listening for the delivered theme to keep its controls honest, ignores it.
 * Wrapped, not aliased, so the two events stay two types in the bindings.
 */
export type OverlayThemeDraft = { resolved: ResolvedOverlayTheme }
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
/**
 * A state the preview can show, or `Cycle` to loop through all of them. These
 * are the overlay's own states under both names it uses for capture.
 * `Recording` is the Minimal pill's, `Listening` the Live panel's. Asking for
 * the other style's name is not an error, because the driver maps it onto the
 * current style's own.
 */
export type PreviewState = 
/**
 * Loop the whole sequence a real session visits.
 */
"cycle" | 
/**
 * Shown, but no microphone samples yet (the muted pill).
 */
"arming" | 
/**
 * Capturing, Minimal's name for it.
 */
"recording" | 
/**
 * Capturing, Live's name for it (the panel is open, text arriving).
 */
"listening" | 
/**
 * Finalizing the transcript.
 */
"transcribing" | 
/**
 * Post-processing the transcript.
 */
"processing"
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * The whole answer to "how does the overlay look right now".
 * 
 * Both the command result and the event payload, so the overlay's pull on
 * show and the push on change carry the identical type.
 */
export type ResolvedOverlayTheme = { 
/**
 * The theme file's tokens, clamped. `None` still means inherit: the apply
 * layer writes no custom property for it.
 */
theme: OverlayTheme; 
/**
 * Concrete, never `None`: the requested Material downgraded to Flat when
 * Glass is unavailable.
 */
effective_material: Material; 
/**
 * Whether Glass is offerable and whether it can render right now. Read by
 * the Appearance tab instead of a TypeScript platform check, so the two
 * sides cannot disagree.
 */
glass_support: GlassSupport; 
/**
 * How far the overlay window may reach past the card towards the screen
 * edge it is anchored to, in logical points, already scaled and whole.
 * 
 * Derived, like the Material above, and for the same reason: only Rust
 * knows the room the card has to the usable edge on this platform at this
 * overlay position, and the overlay page must inset the card by exactly
 * the same number or the card would move the moment a shadow is switched
 * on. The apply layer writes it straight into `--ov-shadow-edge-slack`;
 * the native window is sized and placed from it. Zero under Glass and
 * whenever the shadow strength is zero.
 */
shadow_edge_slack?: number; 
/**
 * The theme file behind `theme`: where it is, whether Handy writes it,
 * which tokens it sets and what the reader had to ignore.
 */
file: ThemeFileState; 
/**
 * Whether a file watcher is delivering changes to that file. False means
 * the Appearance tab keeps its Reload button, the only way a hand edit
 * reaches the screen then. Process-wide, so it rides here rather than on
 * the file state, which is cached per read.
 */
watching: boolean }
export type SecretMap = Partial<{ [key in string]: string }>
export type SecureInputStatus = { 
/**
 * Secure input is currently enabled (live check)
 */
enabled: boolean; 
/**
 * Enabled continuously long enough to be considered stuck (not just a
 * password field gaining momentary focus)
 */
sustained: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Carbon fallback registrations are currently active
 */
fallback_active: boolean; 
/**
 * Binding ids shadow-registered with identical semantics
 */
covered_bindings: string[]; 
/**
 * Side-specific binding ids widened to match either side while shadowed
 */
degraded_bindings: string[]; 
/**
 * Binding ids that cannot fire at all (e.g. fn+key, registration failure)
 */
uncovered_bindings: string[]; 
/**
 * The user tried to record a shortcut while secure input was active.
 * Treated as user impact even when every binding is covered, so the
 * warning banner appears and explains why recording refused.
 */
recorder_blocked: boolean }
/**
 * How the transcribe shortcut's key events drive a recording.
 */
export type ShortcutActivation = 
/**
 * Press to start, press again to stop.
 */
"toggle" | 
/**
 * Hold to record, release to stop.
 */
"push_to_talk" | 
/**
 * Hold to record and release to stop, or tap to keep recording until the
 * next press. Which one it was is decided by how long the key was held
 * (`hold_threshold_ms`).
 */
"hold_or_toggle"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing — show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
/**
 * UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 * and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark"
/**
 * One thing the theme file got wrong, reported to the Appearance tab.
 * 
 * `Deserialize` is required because this rides in the `resolved-overlay-theme`
 * event payload, and listening for an event deserializes it.
 */
export type ThemeFileDiagnostic = { 
/**
 * What went wrong, as a stable identity the tab can translate.
 */
code: ThemeFileDiagnosticCode; 
/**
 * The token key, or `None` for a document-level problem. Doubles as the
 * parameter for the translated message.
 */
key: string | null; 
/**
 * English, deliberately untranslated. It names JSON keys and values, and
 * goes to the log.
 */
message: string }
/**
 * What kind of thing the theme file got wrong.
 * 
 * A stable, translatable identity for a diagnostic. The Appearance tab looks
 * up an i18n string by code and passes `key` as a parameter, so the user reads
 * their own language while `message` keeps the English detail for the log.
 */
export type ThemeFileDiagnosticCode = 
/**
 * The document is not valid JSON, or not a JSON object.
 */
"malformed_document" | 
/**
 * The document declares a `version` this build does not know; it is parsed
 * best-effort.
 */
"unsupported_version" | 
/**
 * A top-level key that is not a token and not `version`; ignored.
 */
"unknown_key" | 
/**
 * A token whose value is not the JSON type the contract requires.
 */
"wrong_type" | 
/**
 * A colour that is not a `#rrggbb` value this contract accepts.
 */
"invalid_color" | 
/**
 * A number outside the token's bounds; clamped to the nearest bound.
 */
"out_of_bounds" | 
/**
 * The file exists but could not be read (permissions, size, encoding).
 */
"unreadable"
/**
 * Whether the Appearance tab's changes are written to the theme file.
 * 
 * Handy owns the path when it is absent in one of Handy's own locations, or a
 * regular, writable file. Anything else belongs to the user or to a tool, and
 * Handy reads it without ever writing back.
 */
export type ThemeFileOwnership = { 
/**
 * True when a committed change from the Appearance tab writes this path.
 */
writable: boolean; 
/**
 * Why not, when `writable` is false.
 */
reason: ManagedReason | null; 
/**
 * A symlink's target, the one reason carrying a detail. The tab shows it,
 * so the user can find the file really in charge.
 */
target: string | null }
/**
 * What the theme file currently contributes.
 * 
 * Only the theme-file reader reads the file, and it fills this in. Everything
 * downstream consumes this state instead of the document.
 */
export type ThemeFileState = { 
/**
 * The file in effect, or the path Handy would read if one appeared.
 */
path: string; 
/**
 * Whether a theme file was actually found and read at `path`.
 */
present: boolean; 
/**
 * The document's declared `version`, or `None` when it is absent or the
 * file is not present. A missing version means 1.
 */
version: number | null; 
/**
 * The overlay theme this document holds, which is the overlay theme.
 */
tokens: OverlayTheme; 
/**
 * The keys the document actually sets, in contract order. What the tab's
 * "sets N of M values" line counts; the rest of the document's tokens
 * inherit.
 */
owned_keys: string[]; 
/**
 * Whether Handy writes this path, and why not when it does not. A managed
 * file locks every token row in the Appearance tab.
 */
ownership: ThemeFileOwnership; 
/**
 * Everything the reader had to ignore or clamp, in contract order (the
 * token table's, not the document's, since `serde_json` sorts an object's
 * keys unless `preserve_order` is on). Capped at a handful of entries for
 * the payload; `diagnostics_total` is the count before the cap, and every
 * diagnostic reaches the log uncapped.
 */
diagnostics: ThemeFileDiagnostic[]; 
/**
 * How many diagnostics the reader found before `diagnostics` was capped.
 * Equal to `diagnostics.len()` when nothing was capped, larger when the
 * tab needs to say "…and N more", `0` when the file is absent.
 */
diagnostics_total: number; 
/**
 * True when a failed read kept the previous, good document.
 */
stale: boolean }
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type VadBackend = "silero" | "earshot"
/**
 * How the control row's waveform is drawn.
 * 
 * `Bars` is today's nine capsules, the inherit, and the only value drawn as
 * DOM elements; the other five are drawn on one canvas in the waveform lane.
 * The lane is the same width whatever draws in it, so the style never changes
 * the card's footprint and no window is a function of it.
 * 
 * Four of the five read `waveform_width` and one reads `waveform_gap`; the
 * Appearance tab hides the rows a style ignores. `WAVEFORM_STYLE_TOKENS` in
 * `src/overlay/waveform/waveformStyles.ts` is the same table, pinned by
 * `the_waveform_styles_match_the_frontends`.
 */
export type WaveformStyle = 
/**
 * Nine centred capsules, one per bucket, each as tall as its level.
 * Handy's own meter, unchanged, and what an unset token inherits.
 */
"bars" | 
/**
 * One continuous ribbon mirrored about the centre line, its thickness
 * following the levels while a slow drift carries it sideways.
 */
"ribbon" | 
/**
 * A single rounded lozenge whose outline deforms per bucket and breathes
 * with the overall level: one living thing rather than a graph.
 */
"bloom" | 
/**
 * A field of soft round motes drifting up out of the lane, loudness
 * lighting more of them and throwing them further.
 */
"motes" | 
/**
 * A dot-matrix VU: each bucket a column of square dots lit from the
 * centre outward in quantised steps.
 */
"matrix" | 
/**
 * A contiguous stepped histogram, square corners and no gaps, heights
 * quantised to fixed levels.
 */
"steps"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
